# Generated by Django 4.2.7 on 2025-12-12 13:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Departamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("codigo", models.CharField(max_length=10)),
                ("capital", models.CharField(blank=True, max_length=100)),
                ("area_km2", models.FloatField(default=0)),
            ],
            options={
                "verbose_name": "Departamento",
                "verbose_name_plural": "Departamentos",
            },
        ),
        migrations.CreateModel(
            name="Incendio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                (
                    "fecha_deteccion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("latitud", models.FloatField()),
                ("longitud", models.FloatField()),
                ("departamento", models.CharField(max_length=100)),
                ("intensidad", models.FloatField(default=0.5)),
                ("area_afectada", models.FloatField(default=0)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("controlado", "Controlado"),
                            ("extinto", "Extinto"),
                        ],
                        default="activo",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Incendio Forestal",
                "verbose_name_plural": "Incendios Forestales",
            },
        ),
        migrations.CreateModel(
            name="IncendioForestal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del incendio"
                    ),
                ),
                (
                    "fecha_deteccion",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de detección",
                    ),
                ),
                ("fecha_ultima_actualizacion", models.DateTimeField(auto_now=True)),
                ("latitud", models.FloatField(verbose_name="Latitud")),
                ("longitud", models.FloatField(verbose_name="Longitud")),
                (
                    "intensidad",
                    models.FloatField(
                        default=0.5, help_text="Intensidad del incendio (0-1)"
                    ),
                ),
                (
                    "severidad",
                    models.CharField(
                        choices=[
                            ("bajo", "🟢 Bajo"),
                            ("medio", "🟡 Medio"),
                            ("alto", "🟠 Alto"),
                            ("critico", "🔴 Crítico"),
                        ],
                        default="medio",
                        max_length=20,
                    ),
                ),
                (
                    "area_afectada_ha",
                    models.FloatField(
                        default=0, verbose_name="Área afectada (hectáreas)"
                    ),
                ),
                (
                    "confianza_deteccion",
                    models.FloatField(
                        default=0.8, help_text="Confianza en la detección (0-1)"
                    ),
                ),
                (
                    "satelite",
                    models.CharField(
                        default="MODIS", max_length=50, verbose_name="Satélite fuente"
                    ),
                ),
                (
                    "brillo_temperatura",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Temperatura de brillo (°C)"
                    ),
                ),
                (
                    "pixel_size",
                    models.FloatField(default=1.0, verbose_name="Tamaño de pixel (km)"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "🔥 Activo"),
                            ("controlado", "⚠️ Controlado"),
                            ("extinto", "✅ Extinto"),
                        ],
                        default="activo",
                        max_length=20,
                    ),
                ),
                (
                    "fuente_datos",
                    models.CharField(
                        default="NASA FIRMS",
                        max_length=100,
                        verbose_name="Fuente de datos",
                    ),
                ),
                ("notas", models.TextField(blank=True, verbose_name="Observaciones")),
                (
                    "imagen_satelital",
                    models.URLField(blank=True, verbose_name="URL imagen satelital"),
                ),
                (
                    "reporte_pdf",
                    models.FileField(blank=True, null=True, upload_to="reportes/"),
                ),
                (
                    "departamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="monitoreo.departamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Incendio Forestal",
                "verbose_name_plural": "Incendios Forestales",
                "ordering": ["-fecha_deteccion"],
            },
        ),
    ]
