# Generated by Django 4.2.7 on 2025-12-10 05:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Incendio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                (
                    "fecha_deteccion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("latitud", models.FloatField()),
                ("longitud", models.FloatField()),
                ("departamento", models.CharField(max_length=100)),
                ("intensidad", models.FloatField(default=0.5)),
                ("area_afectada", models.FloatField(default=0)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("controlado", "Controlado"),
                            ("extinto", "Extinto"),
                        ],
                        default="activo",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Incendio Forestal",
                "verbose_name_plural": "Incendios Forestales",
            },
        ),
    ]
